# Write the CURRENT git revision of SRC into the header OUT.
#
# Runs in script mode from a custom target so it re-evaluates on every build; an
# execute_process() at configure time would leave a stale revision compiled into
# the binary. (notes: stamp-why-script-mode)
#
# Written only when the contents CHANGE, so an unchanged revision does not
# force a recompile of the translation unit that includes it on every build.
# Moved comments: doc/explo_planner_code_notes.md
if(NOT DEFINED OUT OR NOT DEFINED SRC)
  message(FATAL_ERROR "StampGitRev.cmake requires -DOUT= and -DSRC=")
endif()

set(_rev "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
  # A short hash, not describe --tags: the harness manifest, gate check 3b and
  # equiv_pair.sh all compare this string against rev-parse --short.
  # (notes: stamp-hash-not-describe)
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE _out
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(_rc EQUAL 0 AND NOT _out STREQUAL "")
    set(_rev "${_out}")
    # Appends "-dirty", which gate check 3c reads. status --porcelain counts
    # untracked files too, matching equiv_pair.sh's dirt test.
    # (notes: stamp-dirty-marker)
    execute_process(
      COMMAND ${GIT_EXECUTABLE} status --porcelain
      WORKING_DIRECTORY "${SRC}"
      OUTPUT_VARIABLE _dirt
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET
      RESULT_VARIABLE _drc)
    if(_drc EQUAL 0 AND NOT _dirt STREQUAL "")
      set(_rev "${_rev}-dirty")
    endif()
  endif()
endif()

# "unknown" is deliberately NOT a build failure: a release tarball or a vendored
# copy has no .git and must still build. The experiment gate is what refuses to
# score a run whose binary could not say what it was built from — a build-time
# refusal here would only push people to build outside git.
set(_body "// Generated by cmake/StampGitRev.cmake on every build. Do not edit.
#pragma once
#define EXPLO_PLANNER_GIT_REV \"${_rev}\"
")

set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _body)
  file(WRITE "${OUT}" "${_body}")
  message(STATUS "explo_planner git revision: ${_rev}")
endif()
