# Write the CURRENT git revision of SRC into the header OUT.
#
# Run in script mode (`cmake -P`) from a custom target, so it re-evaluates on
# every build. The obvious spelling — execute_process() at the top of
# CMakeLists.txt — runs once, when the build tree is CONFIGURED, and never
# again: editing a source file and rebuilding leaves the old revision compiled
# into the binary. That is not a theoretical decay. Campaign cr5 ran a binary
# stamped 6ce7ad0 while its manifest recorded 1a097dc, because the build tree
# had been configured at P5 and every commit since had only rebuilt. The gate's
# check 3b compares those two and could not pass on any cell.
#
# Written only when the contents CHANGE, so an unchanged revision does not
# force a recompile of the translation unit that includes it on every build.
if(NOT DEFINED OUT OR NOT DEFINED SRC)
  message(FATAL_ERROR "StampGitRev.cmake requires -DOUT= and -DSRC=")
endif()

set(_rev "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
  # A HASH, deliberately, and not `describe --tags`. Every consumer of this
  # string matches it against a hash: the harness manifest records
  # git_explo_planner from `git rev-parse --short`, gate check 3b asserts the
  # manifest startswith the baked rev's first seven characters, and
  # equiv_pair.sh requires exact equality with `rev-parse --short` to prove a
  # rebuild happened. The old spelling carried --tags, which is harmless only
  # while the repo has no tags: the first `git tag v1.0` would stamp binaries
  # "v1.0-dirty", check 3b would hard-fail every cell of the campaign running
  # at the time, and the cause would look nothing like the tag that caused it.
  execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE _out
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(_rc EQUAL 0 AND NOT _out STREQUAL "")
    set(_rev "${_out}")
    # The "-dirty" marker, which rev-parse does not provide and gate check 3c
    # exists to read: a campaign whose binary was built from uncommitted work
    # is not reproducible from any commit. `status --porcelain` counts
    # untracked files too, matching equiv_pair.sh's dirt test — an untracked
    # source file survives `git checkout` and would compile into both sides of
    # a supposedly-controlled comparison.
    execute_process(
      COMMAND ${GIT_EXECUTABLE} status --porcelain
      WORKING_DIRECTORY "${SRC}"
      OUTPUT_VARIABLE _dirt
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET
      RESULT_VARIABLE _drc)
    if(_drc EQUAL 0 AND NOT _dirt STREQUAL "")
      set(_rev "${_rev}-dirty")
    endif()
  endif()
endif()

# "unknown" is deliberately NOT a build failure: a release tarball or a vendored
# copy has no .git and must still build. The experiment gate is what refuses to
# score a run whose binary could not say what it was built from — a build-time
# refusal here would only push people to build outside git.
set(_body "// Generated by cmake/StampGitRev.cmake on every build. Do not edit.
#pragma once
#define EXPLO_PLANNER_GIT_REV \"${_rev}\"
")

set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _body)
  file(WRITE "${OUT}" "${_body}")
  message(STATUS "explo_planner git revision: ${_rev}")
endif()
